create table ads_data_joined
(
    campaign_id                        text,
    campaign_name                      text,
    submission_date                    text,
    description                        text,
    campaign_objectives                text,
    kpis                               text,
    placements                         text,
    start_date                         text,
    end_date                           text,
    serving_locations                  text,
    black_white_audience_list_included text,
    delivery_requirements              text,
    cost_centre                        text,
    currency                           text,
    buy_rate                           double precision,
    volume_agreed                      double precision,
    gross_cost                         double precision,
    agency_fee                         text,
    percentage                         double precision,
    flat_fee                           double precision,
    net_cost                           double precision,
    type                               text,
    width                              text,
    height                             text,
    creative_id                        text,
    auction_id                         text,
    browser_ts                         text,
    game_key                           text,
    geo_country                        text,
    site_name                          text,
    platform_os                        text,
    device_type                        text,
    browser                            text,
    labels                             json,
    text                               json,
    colors                             json,
    video_data                         json,
    eng_type                           json,
    direction                          json,
    adunit_size                        json
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;